- name: Create application directory.
  ansible.builtin.file:
    path: "{{ application_path }}"
    state: directory

- name: Copy Dockerfiles.
  ansible.builtin.copy:
    src: "{{ item }}/"
    dest: "{{ application_path }}/{{ item }}/"
  loop:
    - grafana
    - influxdb
    - nginx
    - telegraf
  
- name: Prepare influxdb configuration.
  ansible.builtin.template:
    src: "env.influxdb.j2"
    dest: "{{ application_path }}/env.influxdb"

- name: Prepare telegraf configuration.
  ansible.builtin.template:
    src: "telegraf.conf.j2"
    dest: "{{ application_path }}/telegraf/config/telegraf.conf"

- name: Prepare docker-compose.
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ application_path }}/docker-compose.yml"