- name: Create application directory.
  ansible.builtin.file:
    path: "{{ application_path }}"
    state: directory

- name: Copy Dockerfiles.
  ansible.builtin.copy:
    src: "{{ item }}/"
    dest: "{{ application_path }}/{{ item }}/"
  loop:
    - grafana
    - influxdb
    - nginx
    - telegraf
  
- name: Prepare influxdb configuration.
  ansible.builtin.template:
    src: "env.influxdb.j2"
    dest: "{{ application_path }}/env.influxdb"

- name: Create telegraf configuration directory.
  ansible.builtin.file:
    path: "{{ application_path }}/telegraf/config/"
    state: directory

- name: Prepare telegraf configuration.
  ansible.builtin.template:
    src: "telegraf.conf.j2"
    dest: "{{ application_path }}/telegraf/config/telegraf.conf"

- name: Create grafana configuration directory.
  ansible.builtin.file:
    path: "{{ application_path }}/grafana/provisioning/datasources/"
    state: directory

- name: Prepare grafana configuration.
  ansible.builtin.template:
    src: "influxdb_ds.yml.j2"
    dest: "{{ application_path }}/grafana/provisioning/datasources/influxdb_ds.yml"

- name: Prepare docker-compose configuration.
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ application_path }}/docker-compose.yml"

- name: Start application.
  community.docker.docker_compose:
    project_src: "{{ application_path }}"
    state: present