{
 "title": "VMware vSphere  - Overview",
 "description": "VMware vSphere Dashboard (Grafana 9.x / InfluxDB v2.0)",
 "tags": [
  "VMware",
  "vSphere Overview",
  "vSphere Telegraf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "20s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "vcenter",
    "label": "vCenter Server",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_cpu\")\r\n  |> keep(columns: [\"vcenter\"])\r\n  |> distinct(column: \"vcenter\")\r\n  |> group()"
   },
   {
    "name": "clustername",
    "label": "Cluster",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_cluster_cpu\")\r\n  |> filter(fn: (r) => r[\"clustername\"] != \"\")\r\n  |> filter(fn: (r) => r[\"vcenter\"] == \"${vcenter}\")\r\n  |> keep(columns: [\"clustername\"])\r\n  |> distinct(column: \"clustername\")\r\n  |> group()\r\n"
   },
   {
    "name": "esxi",
    "label": "ESXi Server",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_cpu\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] != \"\")\r\n  |> filter(fn: (r) => r[\"vcenter\"] == \"${vcenter}\")\r\n  |> keep(columns: [\"esxhostname\"])\r\n  |> distinct(column: \"esxhostname\")\r\n  |> group()"
   },
   {
    "name": "datastore",
    "label": "Datastore",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_datastore_disk\")\r\n  |> filter(fn: (r) => r[\"dsname\"] != \"\")\r\n  |> filter(fn: (r) => r[\"vcenter\"] == \"${vcenter}\")\r\n  |> keep(columns: [\"dsname\"])\r\n  |> distinct(column: \"dsname\")\r\n  |> group()"
   },
   {
    "name": "virtualmachine",
    "label": "VM",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_cpu\")\r\n  |> filter(fn: (r) => r[\"vmname\"] != \"\")\r\n  |> filter(fn: (r) => r[\"vcenter\"] == \"${vcenter}\")\r\n  |> keep(columns: [\"vmname\"])\r\n  |> distinct(column: \"vmname\")\r\n  |> group()"
   }
  ]
 },
 "panels": [
  {
   "title": "Datacenter Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "vSphere Overview",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "vCenter Summary",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_cpu\")\r\n  |> keep(columns: [\"vcenter\"])\r\n  |> distinct(column: \"vcenter\")\r\n  |> group()\r\n  |> count()\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Cluster Summary",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_cpu\")\r\n  |> keep(columns: [\"clustername\"])\r\n  |> distinct(column: \"clustername\")\r\n  |> group()\r\n  |> count()\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "ESXi Summary",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_cpu\")\r\n  |> keep(columns: [\"esxhostname\"])\r\n  |> distinct(column: \"esxhostname\")\r\n  |> group()\r\n  |> count()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "VM Summary",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_cpu\")\r\n  |> keep(columns: [\"vmname\"])\r\n  |> distinct(column: \"vmname\")\r\n  |> group()\r\n  |> count()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Datastore Summary",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_datastore_disk\")\r\n  |> keep(columns: [\"dsname\"])\r\n  |> distinct(column: \"dsname\")\r\n  |> group()\r\n  |> count()",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$clustername Overview",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
     "repeat": "clustername",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_sys",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_sys\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime_latest\")\r\n  |> filter(fn: (r) => r[\"vcenter\"] =~ /${vcenter:regex}/)\r\n  |> filter(fn: (r) => r[\"clustername\"] =~ /${clustername:regex}/)\r\n  |> group(columns: [\"clustername\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "uptime_latest" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Uptime" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" },
        { "condition": "AND", "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"instance-total\")\r\n  |> filter(fn: (r) => r[\"vcenter\"] =~ /${vcenter:regex}/)\r\n  |> filter(fn: (r) => r[\"clustername\"] =~ /${clustername:regex}/)\r\n  |> group(columns: [\"clustername\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "CPU Usage" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" },
        { "condition": "AND", "key": "clustername", "operator": "=~", "value": "/^$clustername$/" },
        { "condition": "AND", "key": "cpu", "operator": "=", "value": "instance-total" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"vcenter\"] =~ /${vcenter:regex}/)\r\n  |> filter(fn: (r) => r[\"clustername\"] =~ /${clustername:regex}/)\r\n  |> group(columns: [\"clustername\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "RAM Usage" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" },
        { "condition": "AND", "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Cluster CPU Usage %",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_clustername",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "clustername" ], "type": "tag" },
        { "params": [ "cpu" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"instance-total\")\r\n  |> filter(fn: (r) => r[\"clustername\"] =~ /${clustername:regex}/)\r\n  |> group(columns: [\"clustername\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" },
        { "condition": "AND", "key": "cpu", "operator": "=", "value": "instance-total" }
       ]
      }
     ]
    },
    {
     "title": "Cluster RAM Usage in %",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 7, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_clustername",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "clustername" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"clustername\"] =~ /${clustername:regex}/)\r\n  |> group(columns: [\"clustername\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" },
        { "condition": "AND", "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
       ]
      }
     ]
    },
    {
     "title": "Datastores - Usage Capacity",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 11, "x": 13, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_source",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_datastore_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity_latest\" or r[\"_field\"] == \"used_latest\")\r\n  |> filter(fn: (r) => r[\"source\"] =~ /${datastore:regex}/)\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: float(v: r.used_latest) / float(v: r.capacity_latest) * 100.0 }))\r\n  |> group(columns: [\"source\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Cluster Network Usage",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "alias": "$tag_clustername - Received",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "clustername" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_net",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytesRx_average\")\r\n  |> filter(fn: (r) => r[\"clustername\"] =~ /${clustername:regex}/)\r\n  |> group(columns: [\"clustername\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "bytesRx_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
       ]
      },
      {
       "alias": "$tag_clustername - Transmited",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "clustername" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_net",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bytesTx_average\")\r\n  |> filter(fn: (r) => r[\"clustername\"] =~ /${clustername:regex}/)\r\n  |> group(columns: [\"clustername\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n",
       "select": [
        [
         { "params": [ "bytesTx_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
       ]
      }
     ]
    },
    {
     "title": "Cluster Storage Adapter",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 7, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_clustername - ReadAverage",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "clustername" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_storageAdapter",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_storageAdapter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalReadLatency_average\")\r\n  |> group(columns: [\"clustername\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "totalReadLatency_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
       ]
      },
      {
       "alias": "$tag_clustername - WriteAverage",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "clustername" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_storageAdapter",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_storageAdapter\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalWriteLatency_average\")\r\n  |> group(columns: [\"clustername\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "totalWriteLatency_average" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "clustername", "operator": "=~", "value": "/^$clustername$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Datastore Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$datastore",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
     "repeat": "datastore",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "vsphere_datastore_disk",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_datastore_disk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"capacity_latest\" or r[\"_field\"] == \"used_latest\")\r\n  |> filter(fn: (r) => r[\"source\"] =~ /${datastore:regex}/)\r\n  |> group()\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ r with  _value: float(v: r.used_latest) / float(v: r.capacity_latest) * 100.0 }))\r\n  |> group(columns: [\"source\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)",
       "select": [
        [
         { "params": [ "used_latest" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "source", "operator": "=", "value": "ZEXT-NETAPP-01" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Hypervisor Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Hypervisor CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_esxhostname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_cpu",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"instance-total\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"esxhostname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" },
        { "condition": "AND", "key": "cpu", "operator": "=", "value": "instance-total" }
       ]
      }
     ]
    },
    {
     "title": "Hypervisor Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_esxhostname mem usage average",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_mem",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"esxhostname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    },
    {
     "title": "Hypervisor Net Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "alias": "$tag_esxhostname net usage average",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "esxhostname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_host_net",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_host_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"esxhostname\"] =~ /${esxi:regex}/)\r\n  |> group(columns: [\"esxhostname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "esxhostname", "operator": "=~", "value": "/^$esxi$/" }
       ]
      }
     ]
    },
    {
     "title": "vCenter CPU/RAM",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_vcenter CPU",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vcenter" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_cpu",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"guesthostname\"] =~ /${vcenter:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" },
        { "condition": "AND", "key": "cpu", "operator": "=", "value": "instance-total" }
       ]
      },
      {
       "alias": "$tag_vcenter RAM",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vcenter" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_mem",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"guesthostname\"] =~ /${vcenter:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vcenter", "operator": "=~", "value": "/^$vcenter$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Virtual Machine Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Virtual Machine CPU Usage in %",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "cpu" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_cpu",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"cpu\"] == \"instance-total\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" },
        { "condition": "AND", "key": "cpu", "operator": "=", "value": "instance-total" }
       ]
      }
     ]
    },
    {
     "title": "Virtual Machine Memory Usage Avg.",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_mem",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_mem\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "Virtual Machine CPU READY ms",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_cpu",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_cpu\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ready_summation\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "ready_summation" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "Virtual Machine Network Usage Avg (Kbps)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "KBs" } },
     "targets": [
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_net",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_net\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "usage_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "Virtual Machine Disk Performance (Read VMFS Block IOPS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_virtualDisk",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_virtualDisk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"numberReadAveraged_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "numberReadAveraged_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "Virtual Machine Disk Performance (Write VMFS Block IOPS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_virtualDisk",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_virtualDisk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"numberWriteAveraged_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "numberWriteAveraged_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    },
    {
     "title": "Virtual Machine Disk Performance (Block Latency Total)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_virtualDisk",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_virtualDisk\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalReadLatency_average\")\r\n  |> filter(fn: (r) => r[\"vmname\"] =~ /${virtualmachine:regex}/)\r\n  |> group(columns: [\"vmname\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "totalReadLatency_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      },
      {
       "alias": "$tag_vmname",
       "groupBy": [
        { "params": [ "$inter" ], "type": "time" },
        { "params": [ "vmname" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "vsphere_vm_virtualDisk",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vsphere_vm_virtualDisk\" )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"totalWriteLatency_average\")\r\n  |> group(columns: [\"vmname\",\"_field\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
       "select": [
        [
         { "params": [ "totalWriteLatency_average" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "vmname", "operator": "=~", "value": "/^$virtualmachine$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}